INSERT INTO raw_classical_songs(artist,title) VALUES
    ('Ludwig van Beethoven', 'Symphony No. 9'),
    ('Wolfgang Amadeus Mozart', 'Eine kleine Nachtmusik'),
    ('Johann Sebastian Bach', 'Toccata and Fugue in D minor'),
    ('Pyotr Ilyich Tchaikovsky', 'Swan Lake'),
    ('Frederic Chopin', 'Nocturne in E-flat major'),
    ('Antonio Vivaldi', 'The Four Seasons'),
    ('Claude Debussy', 'Clair de Lune'),
    ('Johannes Brahms', 'Hungarian Dance No. 5'),
    ('Franz Schubert', 'Ave Maria'),
    ('Ludwig van Beethoven', 'Moonlight Sonata'),
    ('Wolfgang Amadeus Mozart', 'Requiem'),
    ('Johann Sebastian Bach', 'Brandenburg Concerto No. 3'),
    ('Antonio Vivaldi', 'Gloria'),
    ('Sergei Rachmaninoff', 'Piano Concerto No. 2');
