CREATE TABLE IF NOT EXISTS src_purchases (
    purchase_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    order_id STRING NOT NULL,
    product_id STRING,
    product_name STRING,
    category STRING,
    quantity INT,
    unit_price DECIMAL(10,2),
    amount DECIMAL(10,2) NOT NULL,
    discount_amount DECIMAL(10,2),
    tax_amount DECIMAL(10,2),
    total_amount DECIMAL(10,2),
    currency_code STRING,
    payment_method STRING,
    payment_status STRING,
    purchase_date DATE NOT NULL,
    purchase_timestamp TIMESTAMP(3) NOT NULL,
    shipping_address STRING,
    billing_address STRING,
    promotion_code STRING,
    sales_channel STRING,
    store_location STRING,
    sales_rep_id BIGINT,
    refund_amount DECIMAL(10,2),
    refund_date DATE,
    return_reason STRING,
    customer_satisfaction_score INT,
    created_date TIMESTAMP(3),
    updated_date TIMESTAMP(3),
    PRIMARY KEY (purchase_id) NOT ENFORCED
) DISTRIBUTED BY HASH(purchase_id) INTO 1 BUCKETS
WITH (
    'changelog.mode' = 'upsert',
    'key.avro-registry.schema-context' = '.flink-dev',
    'value.avro-registry.schema-context' = '.flink-dev',
    'key.format' = 'avro-registry',
    'value.format' = 'avro-registry',
    'kafka.retention.time' = '0',
    'kafka.producer.compression.type' = 'snappy',
    'scan.bounded.mode' = 'unbounded',
    'scan.startup.mode' = 'earliest-offset',
    'value.fields-include' = 'all'
);