#!/usr/bin/env python3
"""Adapt canonical Agno skill directories for Cursor, Claude, or Agno runtimes."""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

GENERATED_HEADER = "<!-- generated by adapt-skills; do not edit -->\n\n"

RUNTIME_BLOCK_RE = re.compile(
    r"<!-- runtime:([^>]+) -->\s*(.*?)\s*<!-- /runtime:\1 -->",
    re.DOTALL,
)

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.DOTALL)

SKILL_PACKAGE_DIRS = (
    "flink-skill-common/skill",
    "ksql-to-flink-skill/skill",
    "spark-to-flink-skill/skill",
)

COPY_SUBDIRS = ("references", "scripts", "prompts")


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parent.parent


def parse_skill_name(skill_md: str, fallback: str) -> str:
    match = FRONTMATTER_RE.match(skill_md)
    if not match:
        return fallback
    for line in match.group(1).splitlines():
        if line.strip().startswith("name:"):
            value = line.split(":", 1)[1].strip().strip("'\"")
            if value:
                return value
    return fallback


def adapt_skill_content(content: str, target: str) -> str:
    def _replace_block(match: re.Match[str]) -> str:
        runtimes = [runtime.strip() for runtime in match.group(1).split(",")]
        if target in runtimes:
            return match.group(2).strip()
        return ""

    adapted = RUNTIME_BLOCK_RE.sub(_replace_block, content)
    adapted = re.sub(r"\n{3,}", "\n\n", adapted)
    return adapted


def copy_skill_assets(source_dir: Path, dest_dir: Path) -> None:
    for subdir in COPY_SUBDIRS:
        src = source_dir / subdir
        if not src.is_dir():
            continue
        dst = dest_dir / subdir
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)


def default_output_dir(
    repo_root: Path,
    skill_source: Path,
    skill_name: str,
    target: str,
) -> Path | None:
    if target == "agno":
        return None
    if target == "cursor":
        return repo_root / ".cursor" / "skills" / skill_name
    if target == "claude":
        package_root = skill_source.parent
        return package_root / ".claude" / "skills" / skill_name
    raise ValueError(f"Unknown target: {target}")


def install_dir(target: str, skill_name: str) -> Path:
    home = Path.home()
    if target == "cursor":
        return home / ".cursor" / "skills" / skill_name
    if target == "claude":
        return home / ".claude" / "skills" / skill_name
    raise ValueError(f"Install not supported for target: {target}")


def adapt_one_skill(
    repo_root: Path,
    skill_rel: str,
    target: str,
    out_dir: Path | None,
    install: bool,
) -> Path | None:
    source_dir = repo_root / skill_rel
    skill_md_path = source_dir / "SKILL.md"
    if not skill_md_path.is_file():
        raise FileNotFoundError(f"Missing SKILL.md: {skill_md_path}")

    raw = skill_md_path.read_text(encoding="utf-8")
    skill_name = parse_skill_name(raw, source_dir.parent.name)
    adapted_body = adapt_skill_content(raw, target)

    if target == "agno":
        return None

    destination = out_dir or default_output_dir(repo_root, source_dir, skill_name, target)
    if destination is None:
        return None

    if install:
        destination = install_dir(target, skill_name)

    destination.mkdir(parents=True, exist_ok=True)
    output_md = GENERATED_HEADER + adapted_body
    (destination / "SKILL.md").write_text(output_md, encoding="utf-8")
    copy_skill_assets(source_dir, destination)
    return destination


def discover_skills(repo_root: Path, skill_filter: str | None) -> list[str]:
    packages = [p for p in SKILL_PACKAGE_DIRS if (repo_root / p / "SKILL.md").is_file()]
    if skill_filter is None:
        return packages
    matched = []
    for package in packages:
        skill_md = (repo_root / package / "SKILL.md").read_text(encoding="utf-8")
        name = parse_skill_name(skill_md, Path(package).parent.name)
        if name == skill_filter or Path(package).parent.name == skill_filter:
            matched.append(package)
    if not matched:
        raise ValueError(f"No skill package matches filter: {skill_filter}")
    return matched


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Adapt Agno canonical skills for IDE runtimes.")
    parser.add_argument(
        "--target",
        required=True,
        choices=("agno", "cursor", "claude"),
        help="Runtime to adapt for.",
    )
    parser.add_argument(
        "--skill",
        help="Skill name or package dir name (e.g. validate-flink-sql, ksql-to-flink-skill). Default: all.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        help="Output directory for a single skill (must use with --skill).",
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="Install to ~/.cursor/skills or ~/.claude/skills instead of project paths.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=repo_root_from_script(),
        help="Repository root (default: parent of scripts/).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.out is not None and args.skill is None:
        parser.error("--out requires --skill")
    if args.target == "agno" and (args.install or args.out):
        parser.error("agno target reads canonical skill/ in place; omit --out and --install")

    repo_root = args.repo_root.resolve()
    packages = discover_skills(repo_root, args.skill)
    outputs: list[Path] = []

    for package in packages:
        dest = adapt_one_skill(
            repo_root=repo_root,
            skill_rel=package,
            target=args.target,
            out_dir=args.out.resolve() if args.out else None,
            install=args.install,
        )
        if dest is not None:
            outputs.append(dest)
            print(f"adapted {package} -> {dest}")

    if args.target == "agno":
        print("agno target uses canonical skill/ directories in place (no files written)")
    elif not outputs:
        print("No skills adapted", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
